sudo: required
language: cpp
dist: xenial
before_script:
  - sudo apt -y update
  - sudo apt -y install pandoc build-essential clang python3-pip ninja-build
  - sudo pip3 install setuptools
  - sudo pip3 install meson
env:
  matrix:
    - RCC=gcc RCXX=g++ CFLAGS=-O2 CXXFLAGS=-O2
    - RCC=clang RCXX=clang++ CFLAGS=-O2 CXXFLAGS=-O2
    - RCC=gcc RCXX=g++ CFLAGS="-O2 -pedantic -Wall -Wextra -Werror" CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror"
    - RCC=clang RCXX=clang++ CFLAGS="-O2 -pedantic -Wall -Wextra -Werror" CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror"
    - RCC=gcc RCXX=g++ CFLAGS=-O3 CXXFLAGS=-O3
    - RCC=clang RCXX=clang++ CFLAGS=-O3 CXXFLAGS=-O3
script:
  - CC=$RCC CXX=$RCXX meson setup _build
  - cd _build && meson test
